# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: normalwindow.git-clone-resume
PackageVersion: 0.1.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: gcr.exe
    PortableCommandAlias: gcr
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/normalwindow/git-clone-resume/releases/download/v0.1.2/git-clone-resume-0.1.2.zip
    InstallerSha256: PLACEHOLDER_SHA256
ManifestType: installer
ManifestVersion: 1.9.0